In [75]:
import pandas as pd
import numpy as np
import random

# np.random.seed(42)

# num_households = 300
# months = 24

# data = []

# cities = ["Delhi", "Mumbai", "Kolkata", "Chennai"]

# seasons_map = {
#     1: "Winter", 2: "Winter", 3: "Summer", 4: "Summer",
#     5: "Summer", 6: "Monsoon", 7: "Monsoon", 8: "Monsoon",
#     9: "Monsoon", 10: "Summer", 11: "Winter", 12: "Winter"
# }

# for h in range(1, num_households + 1):

#     house_size = np.random.randint(600, 2500)
#     residents = np.random.randint(2, 6)
#     city = random.choice(cities)
#     base_rate = np.random.uniform(5, 9)

#     for m in range(1, months + 1):

#         # Correct month + year logic
#         month = ((m - 1) % 12) + 1
#         year = 2023 if m <= 12 else 2024
#         season = seasons_map[month]
#         days = 30

#         # Seasonal usage behavior
#         if season == "Summer":
#             temp = np.random.uniform(32, 42)
#             ac_hours = np.random.uniform(6, 10)
#             geyser_hours = np.random.uniform(0, 0.5)
#         elif season == "Winter":
#             temp = np.random.uniform(10, 22)
#             ac_hours = np.random.uniform(0, 2)
#             geyser_hours = np.random.uniform(1, 3)
#         else:  # Monsoon
#             temp = np.random.uniform(24, 32)
#             ac_hours = np.random.uniform(2, 5)
#             geyser_hours = np.random.uniform(0.5, 1.5)

#         # Power ratings
#         ac_power = np.random.uniform(1200, 1800)
#         geyser_power = np.random.uniform(1500, 2500)
#         fridge_power = np.random.uniform(150, 300)
#         wm_power = np.random.uniform(400, 700)
#         tv_power = np.random.uniform(80, 150)
#         fan_power = 75
#         lighting_power = np.random.uniform(200, 600)

#         wm_cycles = np.random.randint(2, 6)
#         tv_hours = np.random.uniform(2, 6)
#         fan_count = np.random.randint(2, 6)

#         # Appliance energy (kWh)
#         ac_kwh = ac_power * ac_hours * days / 1000
#         geyser_kwh = geyser_power * geyser_hours * days / 1000
#         fridge_kwh = fridge_power * 24 * days * 0.4 / 1000
#         wm_kwh = wm_power * wm_cycles * 1.2 / 1000  # realistic
#         tv_kwh = tv_power * tv_hours * days / 1000
#         fan_kwh = fan_power * fan_count * 12 * days / 1000
#         lighting_kwh = lighting_power * 5 * days / 1000

#         total_kwh = (
#             ac_kwh + geyser_kwh + fridge_kwh +
#             wm_kwh + tv_kwh + fan_kwh + lighting_kwh
#         )

#         # Cost calculation
#         ac_cost = ac_kwh * base_rate
#         geyser_cost = geyser_kwh * base_rate
#         fridge_cost = fridge_kwh * base_rate
#         wm_cost = wm_kwh * base_rate
#         tv_cost = tv_kwh * base_rate
#         fan_cost = fan_kwh * base_rate
#         lighting_cost = lighting_kwh * base_rate

#         total_bill = (
#             ac_cost + geyser_cost + fridge_cost +
#             wm_cost + tv_cost + fan_cost + lighting_cost +
#             np.random.normal(0, 100)  # realistic noise
#         )

#         data.append([
#             h, year, month, season,
#             house_size, residents, city, base_rate,
#             temp,
#             ac_kwh, geyser_kwh, fridge_kwh,
#             wm_kwh, tv_kwh, fan_kwh, lighting_kwh,
#             ac_cost, geyser_cost, fridge_cost,
#             wm_cost, tv_cost, fan_cost, lighting_cost,
#             total_kwh, total_bill
#         ])

# columns = [
#     "household_id", "year", "month", "season",
#     "house_size", "residents", "city", "rate",
#     "avg_temp",
#     "ac_kwh", "geyser_kwh", "fridge_kwh",
#     "wm_kwh", "tv_kwh", "fan_kwh", "lighting_kwh",
#     "ac_cost", "geyser_cost", "fridge_cost",
#     "wm_cost", "tv_cost", "fan_cost", "lighting_cost",
#     "total_kwh", "total_bill"
# ]

# df = pd.DataFrame(data, columns=columns)
# df.to_csv("smart_energy_dataset_final.csv", index=False)

# print("Final Production-Ready Dataset Created!")
# print(df.head())

In [76]:
df = pd.read_csv("smart_energy_dataset_temporal.csv")
df.head()

,household_id,year,month,season,house_size,residents,city,rate,avg_temp,ac_kwh,geyser_kwh,fridge_kwh,wm_kwh,tv_kwh,fan_kwh,lighting_kwh,total_kwh,total_bill
0,1,2023,1,Winter,1726,5,Chennai,8.802857,15.531693,0.000000,106.045512,63.36,2.4,11.409245,108.0,60.0,393.219403,3364.366666
1,1,2023,2,Winter,1726,5,Chennai,8.802857,14.838244,0.000000,75.656232,63.36,2.4,10.876316,81.0,60.0,328.369804,3100.930373
2,1,2023,3,Summer,1726,5,Chennai,8.802857,39.632890,230.756807,0.000000,63.36,3.0,15.725556,135.0,60.0,568.579387,3803.214942
3,1,2023,4,Summer,1726,5,Chennai,8.802857,35.047341,236.596170,0.000000,63.36,1.8,17.361484,81.0,60.0,515.146889,4124.278878
4,1,2023,5,Summer,1726,5,Chennai,8.802857,37.413202,234.406855,0.000000,63.36,2.4,14.089829,81.0,60.0,509.704556,4322.482247

In [77]:
df = df.sort_values(by=["household_id", "year", "month"])

In [78]:
df.head()

,household_id,year,month,season,house_size,residents,city,rate,avg_temp,ac_kwh,geyser_kwh,fridge_kwh,wm_kwh,tv_kwh,fan_kwh,lighting_kwh,total_kwh,total_bill
0,1,2023,1,Winter,1726,5,Chennai,8.802857,15.531693,0.000000,106.045512,63.36,2.4,11.409245,108.0,60.0,393.219403,3364.366666
1,1,2023,2,Winter,1726,5,Chennai,8.802857,14.838244,0.000000,75.656232,63.36,2.4,10.876316,81.0,60.0,328.369804,3100.930373
2,1,2023,3,Summer,1726,5,Chennai,8.802857,39.632890,230.756807,0.000000,63.36,3.0,15.725556,135.0,60.0,568.579387,3803.214942
3,1,2023,4,Summer,1726,5,Chennai,8.802857,35.047341,236.596170,0.000000,63.36,1.8,17.361484,81.0,60.0,515.146889,4124.278878
4,1,2023,5,Summer,1726,5,Chennai,8.802857,37.413202,234.406855,0.000000,63.36,2.4,14.089829,81.0,60.0,509.704556,4322.482247

In [155]:
df["next_month_bill"] = df.groupby("household_id")["total_bill"].shift(-1)

In [80]:
df.head()

,household_id,year,month,season,house_size,residents,city,rate,avg_temp,ac_kwh,geyser_kwh,fridge_kwh,wm_kwh,tv_kwh,fan_kwh,lighting_kwh,total_kwh,total_bill,next_month_bill
0,1,2023,1,Winter,1726,5,Chennai,8.802857,15.531693,0.000000,106.045512,63.36,2.4,11.409245,108.0,60.0,393.219403,3364.366666,3100.930373
1,1,2023,2,Winter,1726,5,Chennai,8.802857,14.838244,0.000000,75.656232,63.36,2.4,10.876316,81.0,60.0,328.369804,3100.930373,3803.214942
2,1,2023,3,Summer,1726,5,Chennai,8.802857,39.632890,230.756807,0.000000,63.36,3.0,15.725556,135.0,60.0,568.579387,3803.214942,4124.278878
3,1,2023,4,Summer,1726,5,Chennai,8.802857,35.047341,236.596170,0.000000,63.36,1.8,17.361484,81.0,60.0,515.146889,4124.278878,4322.482247
4,1,2023,5,Summer,1726,5,Chennai,8.802857,37.413202,234.406855,0.000000,63.36,2.4,14.089829,81.0,60.0,509.704556,4322.482247,3864.372050

In [81]:
df = df.dropna()

In [82]:
df.head()

,household_id,year,month,season,house_size,residents,city,rate,avg_temp,ac_kwh,geyser_kwh,fridge_kwh,wm_kwh,tv_kwh,fan_kwh,lighting_kwh,total_kwh,total_bill,next_month_bill
0,1,2023,1,Winter,1726,5,Chennai,8.802857,15.531693,0.000000,106.045512,63.36,2.4,11.409245,108.0,60.0,393.219403,3364.366666,3100.930373
1,1,2023,2,Winter,1726,5,Chennai,8.802857,14.838244,0.000000,75.656232,63.36,2.4,10.876316,81.0,60.0,328.369804,3100.930373,3803.214942
2,1,2023,3,Summer,1726,5,Chennai,8.802857,39.632890,230.756807,0.000000,63.36,3.0,15.725556,135.0,60.0,568.579387,3803.214942,4124.278878
3,1,2023,4,Summer,1726,5,Chennai,8.802857,35.047341,236.596170,0.000000,63.36,1.8,17.361484,81.0,60.0,515.146889,4124.278878,4322.482247
4,1,2023,5,Summer,1726,5,Chennai,8.802857,37.413202,234.406855,0.000000,63.36,2.4,14.089829,81.0,60.0,509.704556,4322.482247,3864.372050

In [83]:
df["prev_bill"] = df.groupby("household_id")["total_bill"].shift(1)
df = df.dropna()

In [84]:
df = pd.get_dummies(df, columns=["city", "season"], drop_first=True)

In [85]:
exclude_cols = ["total_bill", "next_month_bill"]

features = [col for col in df.columns if col not in exclude_cols]

X = df[features]
y = df["next_month_bill"]

In [86]:
from sklearn.model_selection import TimeSeriesSplit

tscv = TimeSeriesSplit(n_splits=5)

In [87]:
import numpy as np
from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor, GradientBoostingRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor

In [101]:
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

In [111]:
svr_model = Pipeline([
    ("scaler", StandardScaler()),
    ("svr", SVR())
])

In [112]:
models = {
    "Linear": LinearRegression(),
    "Ridge": Ridge(alpha=1.0),
    "Lasso": Lasso(alpha=0.1),
    "Decision Tree": DecisionTreeRegressor(random_state=42),
    "Random Forest": RandomForestRegressor(n_estimators=100, random_state=42),
    "AdaBoost": AdaBoostRegressor(n_estimators=100, random_state=42),
    "Gradient Boosting": GradientBoostingRegressor(n_estimators=100, random_state=42),
    "KNN": KNeighborsRegressor(n_neighbors=5),
    "XGBoost": XGBRegressor(n_estimators=300, learning_rate=0.05, random_state=42),
    "SVR": svr_model
}

In [157]:
results = []

for name, model in models.items():

    mae_scores = []
    rmse_scores = []
    r2_scores = []

    for train_index, test_index in tscv.split(X):

        X_train, X_test = X.iloc[train_index], X.iloc[test_index]
        y_train, y_test = y.iloc[train_index], y.iloc[test_index]

        model.fit(X_train, y_train)
        preds = model.predict(X_test)

        mae_scores.append(mean_absolute_error(y_test, preds))
        rmse_scores.append(np.sqrt(mean_squared_error(y_test, preds)))
        r2_scores.append(r2_score(y_test, preds))

    results.append([
        name,
        np.mean(mae_scores),
        np.mean(rmse_scores),
        np.mean(r2_scores)
    ])

In [ ]:
import pandas as pd

results_df = pd.DataFrame(results, columns=["Model", "MAE", "MSE", "R2"])
results_df = results_df.sort_values(by="RMSE")

print(results_df)

               Model         MAE        RMSE        R2
6  Gradient Boosting  154.718195  195.750321  0.896023
8            XGBoost  160.457811  202.314831  0.888325
4      Random Forest  172.918901  219.470110  0.868387
2              Lasso  188.736562  237.799113  0.848531
1              Ridge  188.777227  237.817639  0.848504
0             Linear  188.791252  237.819209  0.848500
5           AdaBoost  220.406362  269.844937  0.804481
3      Decision Tree  245.212137  318.903382  0.717362
7                KNN  317.781241  400.056539  0.572820
9                SVR  463.553568  571.439842  0.147059

In [106]:
svr_pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("svr", SVR())
])

In [107]:
from sklearn.model_selection import RandomizedSearchCV

# Parameter grids
ridge_params = {
    "alpha": np.linspace(0.01, 20, 50)
}

lasso_params = {
    "alpha": np.linspace(0.001, 2, 50)
}

dt_params = {
    "max_depth": [None, 5, 10, 15, 20],
    "min_samples_split": [2, 5, 10, 20],
    "min_samples_leaf": [1, 2, 4]
}

rf_params = {
    "n_estimators": [100, 200, 500],
    "max_depth": [None, 10, 20],
    "min_samples_split": [2, 5, 10],
    "max_features": ["sqrt", "log2", None]
}

gb_params = {
    "n_estimators": [100, 200, 300],
    "learning_rate": [0.01, 0.05, 0.1],
    "max_depth": [3, 4, 5]
}

ada_params = {
    "n_estimators": [50, 100, 200],
    "learning_rate": [0.01, 0.1, 1.0]
}

knn_params = {
    "n_neighbors": [3, 5, 7, 9, 11],
    "weights": ["uniform", "distance"],
    "p": [1, 2]  # Manhattan vs Euclidean
}

xgb_params = {
    "n_estimators": [200, 300, 500],
    "learning_rate": [0.01, 0.05, 0.1],
    "max_depth": [3, 5, 8],
    "subsample": [0.7, 0.8, 1.0],
    "colsample_bytree": [0.7, 0.8, 1.0]
}

svr_params = {
    "svr__kernel": ["linear", "rbf"],
    "svr__C": [0.1, 1, 10, 100],
    "svr__epsilon": [0.01, 0.1, 0.5],
    "svr__gamma": ["scale", "auto"]
}

randomcv_models = [
    ("Ridge", Ridge(), ridge_params),
    ("Lasso", Lasso(max_iter=5000), lasso_params),
    ("DecisionTree", DecisionTreeRegressor(random_state=42), dt_params),
    ("RandomForest", RandomForestRegressor(random_state=42), rf_params),
    ("GradientBoosting", GradientBoostingRegressor(random_state=42), gb_params),
    ("AdaBoost", AdaBoostRegressor(random_state=42), ada_params),
    ("KNN", KNeighborsRegressor(), knn_params),
    ("XGBoost", XGBRegressor(random_state=42), xgb_params),
    ("SVR", svr_pipeline, svr_params)
]

# Hyperparameter tuning loop
model_param = {}

for name, model, params in randomcv_models:

    print(f"\nTuning {name}...")

    random = RandomizedSearchCV(
        estimator=model,
        param_distributions=params,
        n_iter=20,                 # Balanced speed vs search
        cv=tscv,
        scoring="r2",
        verbose=1,
        n_jobs=-1,
        random_state=42
    )

    random.fit(X_train, y_train)

    model_param[name] = {
        "Best Params": random.best_params_,
        "Best R2": random.best_score_
    }

# Print results
for model_name in model_param:
    print(f"\n---------------- Best Params for {model_name} -------------------")
    print(model_param[model_name])

Tuning Ridge...
Fitting 5 folds for each of 20 candidates, totalling 100 fits

Tuning Lasso...
Fitting 5 folds for each of 20 candidates, totalling 100 fits

Tuning DecisionTree...
Fitting 5 folds for each of 20 candidates, totalling 100 fits

Tuning RandomForest...
Fitting 5 folds for each of 20 candidates, totalling 100 fits

Tuning GradientBoosting...
Fitting 5 folds for each of 20 candidates, totalling 100 fits

Tuning AdaBoost...
Fitting 5 folds for each of 9 candidates, totalling 45 fits

c:\Users\KIIT0001\anaconda\Lib\site-packages\sklearn\model_selection\_search.py:317: UserWarning: The total space of parameters 9 is smaller than n_iter=20. Running 9 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

Tuning KNN...
Fitting 5 folds for each of 20 candidates, totalling 100 fits

Tuning XGBoost...
Fitting 5 folds for each of 20 candidates, totalling 100 fits

Tuning SVR...
Fitting 5 folds for each of 20 candidates, totalling 100 fits

---------------- Best Params for Ridge -------------------
{'Best Params': {'alpha': np.float64(6.12938775510204)}, 'Best R2': np.float64(0.8475397483707079)}

---------------- Best Params for Lasso -------------------
{'Best Params': {'alpha': np.float64(0.5313469387755102)}, 'Best R2': np.float64(0.8475984194897419)}

---------------- Best Params for DecisionTree -------------------
{'Best Params': {'min_samples_split': 20, 'min_samples_leaf': 2, 'max_depth': 10}, 'Best R2': np.float64(0.7850659872109941)}

---------------- Best Params for RandomForest -------------------
{'Best Params': {'n_estimators': 200, 'min_samples_split': 2, 'max_features': None, 'max_depth': 20}, 'Best R2': np.float64(0.8630995093986377)}

---------------- Best Params for GradientBoosting -------------------
{'Best Params': {'n_estimators': 200, 'max_depth': 4, 'learning_rate': 0.05}, 'Best R2': np.float64(0.8961649345854313)}

---------------- Best Params for AdaBoost -------------------
{'Best Params': {'n_estimators': 200, 'learning_rate': 1.0}, 'Best R2': np.float64(0.8008554176120095)}

---------------- Best Params for KNN -------------------
{'Best Params': {'weights': 'uniform', 'p': 1, 'n_neighbors': 11}, 'Best R2': np.float64(0.607192636800813)}

---------------- Best Params for XGBoost -------------------
{'Best Params': {'subsample': 1.0, 'n_estimators': 300, 'max_depth': 3, 'learning_rate': 0.05, 'colsample_bytree': 0.8}, 'Best R2': np.float64(0.8991080326740875)}

---------------- Best Params for SVR -------------------
{'Best Params': {'svr__kernel': 'linear', 'svr__gamma': 'scale', 'svr__epsilon': 0.1, 'svr__C': 100}, 'Best R2': np.float64(0.8422037329820272)}

In [108]:
# Ridge
best_ridge = Ridge(alpha=6.12938775510204)
best_ridge.fit(X_train, y_train)

# Lasso
best_lasso = Lasso(alpha=0.5313469387755102, max_iter=5000)
best_lasso.fit(X_train, y_train)

# Decision Tree
best_dt = DecisionTreeRegressor(
    min_samples_split=20,
    min_samples_leaf=2,
    max_depth=10,
    random_state=42
)
best_dt.fit(X_train, y_train)

# Random Forest
best_rf = RandomForestRegressor(
    n_estimators=200,
    min_samples_split=2,
    max_features=None,
    max_depth=20,
    random_state=42
)
best_rf.fit(X_train, y_train)

# Gradient Boosting
best_gb = GradientBoostingRegressor(
    n_estimators=200,
    max_depth=4,
    learning_rate=0.05,
    random_state=42
)
best_gb.fit(X_train, y_train)

# AdaBoost
best_ada = AdaBoostRegressor(
    n_estimators=200,
    learning_rate=1.0,
    random_state=42
)
best_ada.fit(X_train, y_train)

# KNN
best_knn = KNeighborsRegressor(
    n_neighbors=11,
    weights="uniform",
    p=1
)
best_knn.fit(X_train, y_train)

# SVR (with scaling pipeline)
best_svr = Pipeline([
    ("scaler", StandardScaler()),
    ("svr", SVR(
        kernel="linear",
        C=100,
        epsilon=0.1,
        gamma="scale"
    ))
])
best_svr.fit(X_train, y_train)

# XGBoost (Best Model)
best_xgb = XGBRegressor(
    subsample=1.0,
    n_estimators=300,
    max_depth=3,
    learning_rate=0.05,
    colsample_bytree=0.8,
    random_state=42
)
best_xgb.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=3,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=300,
             n_jobs=None, num_parallel_tree=None, ...)

In [110]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import numpy as np
import pandas as pd

models = {
    "Ridge": best_ridge,
    "Lasso": best_lasso,
    "DecisionTree": best_dt,
    "RandomForest": best_rf,
    "GradientBoosting": best_gb,
    "AdaBoost": best_ada,
    "KNN": best_knn,
    "SVR": best_svr,          
    "XGBoost": best_xgb
}

results = []

for name, model in models.items():
    preds = model.predict(X_test)

    r2 = r2_score(y_test, preds)
    mae = mean_absolute_error(y_test, preds)
    rmse = np.sqrt(mean_squared_error(y_test, preds))

    results.append([name, r2, mae, rmse])

final_results = pd.DataFrame(
    results,
    columns=["Model", "R2", "MAE", "RMSE"]
)

# Sort by best R2
final_results = final_results.sort_values(by="R2", ascending=False).reset_index(drop=True)

# Optional: round for cleaner display
final_results = final_results.round(4)

final_results

              Model      R2       MAE      RMSE
0           XGBoost  0.9195  138.8993  177.0367
1  GradientBoosting  0.9180  140.9120  178.7505
2      RandomForest  0.9032  154.4142  194.1273
3      DecisionTree  0.8710  177.2070  224.1619
4             Ridge  0.8575  187.8851  235.6273
5             Lasso  0.8572  187.9231  235.8514
6               SVR  0.8535  186.4213  238.8477
7          AdaBoost  0.8261  214.7025  260.2541
8               KNN  0.6477  300.2159  370.4488

In [1]:
appliance_cols = [
    "ac_kwh", "geyser_kwh", "fridge_kwh",
    "wm_kwh", "tv_kwh", "fan_kwh", "lighting_kwh"
]

for col in appliance_cols:
    cost_col = col.replace("_kwh", "_cost")
    df[cost_col] = df[col] * df["rate"]

NameError: name 'df' is not defined

In [ ]:
cost_cols = [col for col in df.columns if "_cost" in col]

df["appliance_total_cost"] = df[cost_cols].sum(axis=1)

In [ ]:
for col in cost_cols:
    percent_col = col.replace("_cost", "_percent")
    df[percent_col] = (df[col] / df["appliance_total_cost"]) * 100

In [ ]:
sample = df.iloc[0]

appliance_summary = {
    col.replace("_cost", ""): sample[col]
    for col in cost_cols
}

appliance_summary

{'ac': np.float64(0.0),
 'geyser': np.float64(665.991010576847),
 'fridge': np.float64(557.7490338165292),
 'wm': np.float64(21.126857341535196),
 'tv': np.float64(95.74265773729758),
 'fan': np.float64(713.0314352768129),
 'lighting': np.float64(528.1714335383799)}

In [ ]:
sample_costs = {col: sample[col] for col in cost_cols}

top3 = sorted(sample_costs.items(), key=lambda x: x[1], reverse=True)[:3]

top3

[('fan_cost', np.float64(713.0314352768129)),
 ('geyser_cost', np.float64(665.991010576847)),
 ('fridge_cost', np.float64(557.7490338165292))]

In [ ]:
def generate_recommendation(row, threshold=25):
    recommendations = []
    total = row["appliance_total_cost"]
    
    percent_cols = [col for col in row.index if "_percent" in col]
    
    for col in percent_cols:
        appliance = col.replace("_percent", "")
        percent = row[col]
        
        if percent > threshold:
            
            # Calculate required proportional reduction
            reduction_ratio = threshold / percent
            
            # % reduction required
            reduction_percent = (1 - reduction_ratio) * 100
            
            # Estimated saving
            estimated_saving = total * ((percent - threshold) / 100)
            
            recommendations.append(
                f"{appliance.upper()} contributes {percent:.1f}% of your bill. "
                f"To bring it down to {threshold}%, reduce its usage by approx "
                f"{reduction_percent:.1f}%. "
                f"This could save around ₹{estimated_saving:.0f}."
            )
    
    if not recommendations:
        recommendations.append("Your appliance usage is well balanced.")
    
    return recommendations

In [ ]:
sample = df.iloc[1]
generate_recommendation(sample)

['AC contributes 45.4% of your bill. To bring it down to 25%, reduce its usage by approx 45.0%. This could save around ₹914.',
 'FAN contributes 26.6% of your bill. To bring it down to 25%, reduce its usage by approx 6.0%. This could save around ₹71.']

In [ ]:
def smart_energy_assistant(input_dict, threshold=25):

    user_df = pd.DataFrame([input_dict])

    # ---------------------------
    # 1️⃣ Automatic Month Handling
    # ---------------------------
    current_month = input_dict["month"]
    current_year = input_dict["year"]

    if current_month == 12:
        prediction_month = 1
        prediction_year = current_year + 1
    else:
        prediction_month = current_month + 1
        prediction_year = current_year

    user_df["month"] = prediction_month
    user_df["year"] = prediction_year
    user_df["household_id"] = 0

    # ---------------------------
    # 2️⃣ Compute total_kwh
    # ---------------------------
    user_df["total_kwh"] = (
        user_df["ac_kwh"] +
        user_df["geyser_kwh"] +
        user_df["fridge_kwh"] +
        user_df["wm_kwh"] +
        user_df["tv_kwh"] +
        user_df["fan_kwh"] +
        user_df["lighting_kwh"]
    )

    # ---------------------------
    # 3️⃣ One-hot Encoding
    # ---------------------------
    user_df["city_Delhi"] = 1 if input_dict.get("city") == "Delhi" else 0
    user_df["city_Kolkata"] = 1 if input_dict.get("city") == "Kolkata" else 0
    user_df["city_Mumbai"] = 1 if input_dict.get("city") == "Mumbai" else 0
    user_df["season_Summer"] = 1 if input_dict.get("season") == "Summer" else 0
    user_df["season_Winter"] = 1 if input_dict.get("season") == "Winter" else 0

    user_df = user_df[features]

    # ---------------------------
    # 4️⃣ Prediction
    # ---------------------------
    predicted_bill = best_xgb.predict(user_df)[0]

    # ---------------------------
    # 5️⃣ Appliance Breakdown
    # ---------------------------
    rate = input_dict["rate"]

    appliance_cols = [
        "ac_kwh", "geyser_kwh", "fridge_kwh",
        "wm_kwh", "tv_kwh", "fan_kwh", "lighting_kwh"
    ]

    costs = {
        col.replace("_kwh", ""): input_dict[col] * rate
        for col in appliance_cols
    }

    total_cost = sum(costs.values())

    # ---------------------------
    # 6️⃣ Smart Optimization Logic
    # ---------------------------
    recommendations = []

    for appliance, cost in costs.items():

        percent = (cost / total_cost) * 100

        if percent > threshold:

            # Proportional reduction needed
            reduction_ratio = threshold / percent
            reduction_percent = (1 - reduction_ratio) * 100

            # Estimated saving (excess share removed)
            estimated_saving = total_cost * ((percent - threshold) / 100)

            recommendations.append(
                f"{appliance.upper()} contributes {percent:.1f}% of your bill. "
                f"To bring it down to {threshold}%, reduce its usage by approx "
                f"{reduction_percent:.1f}%. "
                f"This could save around ₹{estimated_saving:.0f}."
            )

    if not recommendations:
        recommendations.append("Your appliance usage is well balanced.")

    return {
        "Prediction Month": prediction_month,
        "Prediction Year": prediction_year,
        "Predicted Bill": round(predicted_bill, 2),
        "Appliance Costs": costs,
        "Recommendations": recommendations
    }

In [ ]:
user_input = {
    "house_size": 1200,
    "residents": 4,
    "rate": 8,
    "avg_temp": 25,
    "ac_kwh": 120,
    "geyser_kwh": 70,
    "fridge_kwh": 40,
    "wm_kwh": 30,
    "tv_kwh": 35,
    "fan_kwh": 40,
    "lighting_kwh": 45,
    "prev_bill": 3200,
    "month": 1,
    "year": 2024,
    "city": "Delhi",
    "season": "Summer"
}

In [ ]:
features = X_train.columns.tolist()
features

['household_id',
 'year',
 'month',
 'house_size',
 'residents',
 'rate',
 'avg_temp',
 'ac_kwh',
 'geyser_kwh',
 'fridge_kwh',
 'wm_kwh',
 'tv_kwh',
 'fan_kwh',
 'lighting_kwh',
 'total_kwh',
 'prev_bill',
 'city_Delhi',
 'city_Kolkata',
 'city_Mumbai',
 'season_Summer',
 'season_Winter']

In [ ]:
result = smart_energy_assistant(user_input)

print(f"Predicted Bill for {result['Prediction Month']}/{result['Prediction Year']}: ₹{result['Predicted Bill']}")

print("\nAppliance Cost Breakdown:")
for k, v in result["Appliance Costs"].items():
    print(f"{k.upper()}: ₹{v}")

print("\nOptimization Suggestions:")
for rec in result["Recommendations"]:
    print("-", rec)

Predicted Bill for 2/2024: ₹3645.77001953125

Appliance Cost Breakdown:
AC: ₹960
GEYSER: ₹560
FRIDGE: ₹320
WM: ₹240
TV: ₹280
FAN: ₹320
LIGHTING: ₹360

Optimization Suggestions:
- AC contributes 31.6% of your bill. To bring it down to 25%, reduce its usage by approx 20.8%. This could save around ₹200.

In [ ]:
import joblib

joblib.dump(best_xgb, "best_xgb.pkl")

['best_xgb.pkl']

In [ ]:
import pandas as pd
import numpy as np

data = {
    "Model": [
        "Linear Regression",
        "Ridge",
        "Lasso",
        "Decision Tree",
        "Random Forest",
        "Gradient Boosting",
        "AdaBoost",
        "KNN",
        "XGBoost",
        "SVR"
    ],
    "R2_Before_Tuning": [
        0.8485,
        0.8485,
        0.8485,
        0.7174,
        0.8684,
        0.8960,
        0.8045,
        0.5728,
        0.8883,
        0.1471
    ],
    "R2_After_Tuning": [
        np.nan,   # Linear not tuned
        0.8575,
        0.8572,
        0.8710,
        0.9032,
        0.9180,
        0.8261,
        0.6477,
        0.9195,
        0.8535
    ]
}

comparison_df = pd.DataFrame(data)

# Sort by R2_After_Tuning descending
comparison_df_sorted = comparison_df.sort_values(
    by="R2_After_Tuning",
    ascending=False,
    na_position="last"
)

comparison_df_sorted.reset_index(drop=True)

               Model  R2_Before_Tuning  R2_After_Tuning
0            XGBoost            0.8883           0.9195
1  Gradient Boosting            0.8960           0.9180
2      Random Forest            0.8684           0.9032
3      Decision Tree            0.7174           0.8710
4              Ridge            0.8485           0.8575
5              Lasso            0.8485           0.8572
6                SVR            0.1471           0.8535
7           AdaBoost            0.8045           0.8261
8                KNN            0.5728           0.6477
9  Linear Regression            0.8485              NaN